In [1]:
# Working on testing out different ML models for the dataset

In [1]:
# Import dependencies
from path import Path
import numpy as np
import pandas as pd

In [23]:
# import 

from AWS_DB import get_data
data = get_data()
data = pd.DataFrame(data)
data.head()

0      1      2  3    4     5    6     7  8  9 10 11 12 13     14
0  65982  94193  19458  1  168  72.0  120    80  3  3  0  0  1  0  25.51
1  33263  47534  19592  1  157  86.0  180  1000  2  2  0  0  1  1  34.89
2  38454  54904  20550  2  168  65.0  130    90  1  1  0  0  1  1  23.03
3  46033  65752  19080  1  172  72.0  120    80  1  1  0  0  1  0  24.34
4  16942  24217  17544  1  155  83.0  150    90  1  1  0  0  1  1  34.55

In [3]:
# Import the dataset 
df = pd.read_csv("cardio_complete.csv")
df.head()

Unnamed: 0  id    age  gender  height  weight  systolic_bp  diastolic_bp  \
0           0   0  18393       2     168    62.0          110            80   
1           1   1  20228       1     156    85.0          140            90   
2           2   2  18857       1     165    64.0          130            70   
3           3   3  17623       2     169    82.0          150           100   
4           4   4  17474       1     156    56.0          100            60   

   cholesterol  gluc  smoke  alco  active  cardio    BMI  
0            1     1      0     0       1       0  21.97  
1            3     1      0     0       1       1  34.93  
2            3     1      0     0       0       1  23.51  
3            1     1      0     0       1       1  28.71  
4            1     1      0     0       0       0  23.01

In [4]:
# remove the column : Unnamed:0
# df.columns

del df["Unnamed: 0"] #-> #quoted out after running successfully.

# check to make sure it's gone.
df.head(5)

id    age  gender  height  weight  systolic_bp  diastolic_bp  cholesterol  \
0   0  18393       2     168    62.0          110            80            1   
1   1  20228       1     156    85.0          140            90            3   
2   2  18857       1     165    64.0          130            70            3   
3   3  17623       2     169    82.0          150           100            1   
4   4  17474       1     156    56.0          100            60            1   

   gluc  smoke  alco  active  cardio    BMI  
0     1      0     0       1       0  21.97  
1     1      0     0       1       1  34.93  
2     1      0     0       0       1  23.51  
3     1      0     0       1       1  28.71  
4     1      0     0       0       0  23.01

In [5]:
# splitting the df into two - target variable (cardio) and the features sans cardio.

y = df["cardio"]
X = df.drop(columns="cardio")

In [6]:
# checking on target variable 
y.head(5)
#looks good

0    0
1    1
2    1
3    1
4    0
Name: cardio, dtype: int64

In [7]:
# checking on features 

X.head()

id    age  gender  height  weight  systolic_bp  diastolic_bp  cholesterol  \
0   0  18393       2     168    62.0          110            80            1   
1   1  20228       1     156    85.0          140            90            3   
2   2  18857       1     165    64.0          130            70            3   
3   3  17623       2     169    82.0          150           100            1   
4   4  17474       1     156    56.0          100            60            1   

   gluc  smoke  alco  active    BMI  
0     1      0     0       1  21.97  
1     1      0     0       1  34.93  
2     1      0     0       0  23.51  
3     1      0     0       1  28.71  
4     1      0     0       0  23.01

In [12]:
# splitting data up into the _train, _test ***USING RANDOM STATE 1
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state= 1, stratify= y)

X_train.shape
    # looks good- 52500, 13 for the train.

(52500, 13)

In [13]:
X_test.shape
    # again, looks good. 17500, 13

(17500, 13)

In [14]:
# take a quick look at y_train -> looks good.
y_train.shape

(52500,)

In [ ]:
# CREATING THE LOGISTIC REGRESSION MODEL

In [15]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver ='lbfgs',
                                max_iter=200,
                                random_state=1)

In [16]:
# Fit (Train) the data 
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=200, random_state=1)

In [ ]:
# Make a predictions DF

In [18]:
# y_pred = classifier.predict(X_test)
# results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
# results.head(20)

y_prediction = classifier.predict(X_test)
results = pd.DataFrame({"Prediction": y_prediction, "Actual": y_test}).reset_index(drop=True)
results.head(25)

Prediction  Actual
0            1       0
1            1       1
2            1       0
3            1       1
4            1       1
5            1       1
6            0       0
7            0       1
8            1       1
9            0       0
10           1       0
11           0       0
12           0       0
13           1       1
14           0       1
15           0       0
16           1       0
17           0       1
18           1       0
19           1       1
20           1       0
21           0       1
22           1       1
23           1       1
24           0       0

In [20]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_prediction))


0.7131428571428572


In [ ]:
# SECTION ABOVE IS FOR LOGISTIC REGRESSSION | ACCURACY SCORE WAS .713

In [ ]:
# RANDOM FOREST WORK 

In [8]:
# Imports for random forest

import pandas as pd
from path import Path
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [ ]:
# Import the dataset 
# df = pd.read_csv("cardio_complete.csv")
# df.head()

In [ ]:
# #                        remove the column : Unnamed:0

# # df.columns

# del df["Unnamed: 0"] #-> quoted out after running successfully.

# # check to make sure it's gone.

# df.head(5)

In [ ]:
# splitting the df into two - target variable (cardio) and the features sans cardio.

# y = df["cardio"]
# X = df.drop(columns="cardio")

In [ ]:
# outcome- check it (series)

In [9]:
# Features - outcome 

X.head()

id    age  gender  height  weight  systolic_bp  diastolic_bp  cholesterol  \
0   0  18393       2     168    62.0          110            80            1   
1   1  20228       1     156    85.0          140            90            3   
2   2  18857       1     165    64.0          130            70            3   
3   3  17623       2     169    82.0          150           100            1   
4   4  17474       1     156    56.0          100            60            1   

   gluc  smoke  alco  active    BMI  
0     1      0     0       1  21.97  
1     1      0     0       1  34.93  
2     1      0     0       0  23.51  
3     1      0     0       1  28.71  
4     1      0     0       0  23.01

In [10]:
# # splitting data up into the _train, _test ***USING RANDOM STATE 1
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state= 1)

X_train.shape
#     # looks good- 52500, 13 for the train.

(52500, 13)

In [11]:
# Scale 


# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler w/ training data.
X_scaler = scaler.fit(X_train)

# Scaling the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)


In [12]:
# Fit the random forest model 

# Create a random forest classifier.

randomforest_model = RandomForestClassifier(n_estimators=500, random_state=1)
# changed from 128 to 500 per module.
# n_estimators -> sets # of trees to be created. use between 64-128 or don't?

In [13]:
# fitting the model
randomforest_model = randomforest_model.fit(X_train_scaled, y_train)
randomforest_model

RandomForestClassifier(n_estimators=500, random_state=1)

In [14]:
# Making predictions using the testing data
predictions = randomforest_model.predict(X_test_scaled)
predictions

array([1, 0, 1, ..., 1, 1, 0])

In [15]:
# Eval the model using confusion_matrix

# Calculating the confusion matrix
cm = confusion_matrix(y_test, predictions)
cm

array([[6519, 2090],
       [2646, 6245]])

In [17]:
# Create a Df from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual True", "Actual False"], columns=["Predicted True", "Predicted False"])
cm_df

Predicted True  Predicted False
Actual True             6519             2090
Actual False            2646             6245

In [18]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)

In [19]:
# Displaying results
print("Confusion Martix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification_Report")
print(classification_report(y_test, predictions))

Confusion Martix


Predicted True  Predicted False
Actual True             6519             2090
Actual False            2646             6245

Accuracy Score : 0.7293714285714286
Classification_Report
              precision    recall  f1-score   support

           0       0.71      0.76      0.73      8609
           1       0.75      0.70      0.73      8891

    accuracy                           0.73     17500
   macro avg       0.73      0.73      0.73     17500
weighted avg       0.73      0.73      0.73     17500



In [20]:
# Calculate feature importance ranking in the Random Forest model.
importances = randomforest_model.feature_importances_
importances

# out is array of scores for the features in the X_test set (sum = 1.0)

array([0.15228444, 0.18888656, 0.01449578, 0.09227503, 0.09839906,
       0.15885806, 0.08675548, 0.03656239, 0.01460138, 0.00755106,
       0.00641202, 0.0118791 , 0.13103965])

In [22]:
# Can sort features by their importance
sorted(zip(randomforest_model.feature_importances_, X.columns), reverse=True)

# the sorted function will sort the zipped list of features
# with their column name (X.columns) in reverse order—
# more important features first—with reverse=True.

[(0.18888656019614947, 'age'),
 (0.15885806339902636, 'systolic_bp'),
 (0.15228443647891485, 'id'),
 (0.13103965326701866, 'BMI'),
 (0.09839905740991194, 'weight'),
 (0.09227502508324939, 'height'),
 (0.08675547534587458, 'diastolic_bp'),
 (0.0365623906979442, 'cholesterol'),
 (0.014601380866102295, 'gluc'),
 (0.014495776496781477, 'gender'),
 (0.011879099536224987, 'active'),
 (0.0075510634667816465, 'smoke'),
 (0.006412017756020087, 'alco')]

In [ ]:
# consider dropping the lower ranked features.

# create a seperate NB for this just to keep track.

In [ ]:
# fill in with those that aren't highly predictive 
X_df_drop = X.drop(columns=["a","b", "c", "d"], axis=1)